language: cpp
compiler:
  - gcc
  #- clang

os:
  - linux
  #- osx

# require Ubuntu 14.04 Trusty Tahr
sudo: required
dist: trusty

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update  -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++ libgtk2.0-dev libopenal-dev libgl1-mesa-dev libwebp-dev libconfig++-dev libconfig-dev libxpm-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev; fi

install: true

script: $CXX --version && make
