language: cpp
compiler:
  - gcc
  #- clang

os:
  - linux
  #- osx

env:
  - MY_TARGET=linux
  - MY_TARGET=android

# require Ubuntu 14.04 Trusty Tahr
sudo: required
dist: trusty

before_install:
  - if [[ "$MY_TARGET" == "linux"   && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update  -qq; else echo "Skipping step for current target..."; fi
  - if [[ "$MY_TARGET" == "linux"   && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++ libgtk2.0-dev libopenal-dev libgl1-mesa-dev libwebp-dev libconfig++-dev libconfig-dev libxpm-dev; else echo "Skipping step for current target..."; fi
  - if [[ "$MY_TARGET" == "linux"   && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev; else echo "Skipping step for current target..."; fi

install: true

script:
  - if [[ "$MY_TARGET" == "linux"   && "$TRAVIS_OS_NAME" == "linux" ]]; then ./contentiousIntegration/build_sview_linux.sh;   else echo "Skipping step for current target..."; fi
  - if [[ "$MY_TARGET" == "android" && "$TRAVIS_OS_NAME" == "linux" ]]; then ./contentiousIntegration/build_sview_android.sh; else echo "Skipping step for current target..."; fi
