name: Build (Ubuntu 24.04)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ \
          libgtk2.0-dev \
          libopenal-dev \
          libgl-dev \
          libwebp-dev \
          libconfig++-dev libconfig-dev \
          libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Compile
      run: |
        ./continuousIntegration/build_sview_linux.sh
